### ISSUE TITLE
can't find the csv files or requirements

### ISSUE THREAD

**Issue by alexrhmatthews** [elgazzarr/fMRI-GNNs#2]
We tried to replicate your data processing, but we couldn't find the example csv files mentioned in the readme in the repository.
The requirements.txt file also seems to be missing.

**Comment by elgazzarr** [comment]
Hey Alex, 
apologies for this. I have created a new version of this repo where you can find the csv files and the requirements. 
Kindly find the new repo [here](https://github.com/elgazzarr/fMRIGNNs).
